//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class archives
    {
        public int adKod { get; set; }
        public Nullable<int> userKod { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string area { get; set; }
        public string color { get; set; }
        public string shape { get; set; }
        public string material { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> isFound { get; set; }
        public byte[] image { get; set; }
        public string typeArea { get; set; }
        public string transportation { get; set; }
    }
}
