//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Advertisement = new HashSet<Advertisement>();
            this.Categories1 = new HashSet<Categories>();
        }
    
        public int categoryKod { get; set; }
        public string categoryName { get; set; }
        public Nullable<int> categoryParentsId { get; set; }
    
        public virtual ICollection<Advertisement> Advertisement { get; set; }
        public virtual ICollection<Categories> Categories1 { get; set; }
        public virtual Categories Categories2 { get; set; }
    }
}
